### PR TITLE
Fix search bug with Sphinx>=7.2

### LINKED ISSUE #274: Search broken due to JavaScript "undefined"
At some point, the search has been broken (the built-in search, not algolia from the wagtail docs).

It is injecting "undefined" into the URLs when jumping to a specific page.

I'll investigate later whether this is due to a sphinx change or a JS change in our theme.

Example: https://docs.coderedcorp.com/wagtail-crx/index.html

* Search for "Contributing", select the suggested "Contributing" page (click or press enter).
* The page 404s. The URL contains an "undefined" which is causing the breakage.
   ```
   # Search URL
   https://docs.coderedcorp.com/wagtail-crx/undefinedcontributing/index.html

   # Real URL
   https://docs.coderedcorp.com/wagtail-crx/contributing/index.html
   ```

image

### PR DESCRIPTION
**Pull request by vsalvino**
Fixes #274 

See relevant change in sphinx: https://github.com/sphinx-doc/sphinx/commit/8e730ae303ae686705ea12f44ef11da926a87cf5

### CODE REVIEW

File: js/theme.js [hunk 1]
```diff
@@ -64,6 +64,18 @@ document.addEventListener('DOMContentLoaded', () => {
...
+  // Prior to Sphinx 7.2, URL_ROOT was part of DOCUMENTATION_OPTIONS.
+  let URL_ROOT = "";
+  // Sphinx >= 7.2
+  if (document.documentElement.dataset.content_root) {
+    URL_ROOT = document.documentElement.dataset.content_root;
+  }
+  // Sphinx < 7.2
+  else if (typeof DOCUMENTATION_OPTIONS.URL_ROOT !== 'undefined') {
+    URL_ROOT = DOCUMENTATION_OPTIONS.URL_ROOT;
+  }
```
Comment (laymonage) [inline js/theme.js:77]: And then the reason why we need to make JS changes, is because this is a custom "autocomplete" implementation using the `autocompleter` JS package. This comes from the Typo3 docs theme that we forked (you can still see remnants of this, e.g. `window.T3Docs`).

Sphinx does not provide autocomplete – the default behaviour is that submitting the search box will direct the browser to the `search.html` page with the `q` parameter added, e.g. https://sphinx-wagtail-theme.readthedocs.io/en/v6.3.0/search.html?q=contributing. This page will then work on the client-side using Sphinx's search index, powered by the `searchtools.js` that [comes from the `basic` theme](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/searchtools.js) and is included in https://github.com/wagtail/sphinx-wagtail-theme/blob/db925d85c2c260a55817da5048e30a667e64c0b7/sphinx_wagtail_theme/layout.html#L184

In fact this is also referred a few lines below:

https://github.com/wagtail/sphinx-wagtail-theme/blob/db925d85c2c260a55817da5048e30a667e64c0b7/js/theme.js#L119-L120

The `searchtools.js` API is undocumented, hence why we need to keep track of the changes in our theme's JS file. See also https://groups.google.com/g/sphinx-users/c/qtLQXDDHbYo

Typo3's theme never runs into this issue because [they pin their Sphinx version to <5](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/blob/5c80df89e833eddff14458c2c3fe56a8a602fee9/requirements_dev.txt#L1) 🫠

**Review by laymonage — APPROVED** [review]
Thank you for digging into this! Sorry it's taking so long to review this. @Stormheg and I looked into this during DjangoCon US this year, but we were wondering why we're depending on Sphinx's undocumented internals, and whether we should look into doing a proper fix that does not rely on undocumented APIs rather than patching it every time it breaks.

To summarise, there are two issues here:

- Missing `data-content_root` on the `<html>` element.
  - This breaks the built-in Sphinx search, i.e. the one that's done via the `search.html` e.g. https://sphinx-wagtail-theme.readthedocs.io/en/v6.3.0/search.html?q=contributing (NOT the autocomplete, although that one breaks too). The search works, but it doesn't give you a context paragraph of each result.
  - Proper fix: our `layout.html` should've extended `basic/layout.html` instead of rolling our own completely. This was already the case from Typo3's theme. Making it extend the basic layout would need some careful refactoring, I think. In the meantime I think it's better to apply this change in our `layout.html` as a quick fix.
- Broken links in the autocompleter, adding `undefined` to the results URL.
  - This is a result of the missing `data-content_root` attribute above. However, only adding the attribute won't fix the autocomplete. Some JS code changes are needed, because the custom autcomplete implementation relied on Sphinx's old behaviour. See my comment for more details.
  - Proper fix: well, it's debatable what the proper fix is. Autocomplete is a custom feature from Typo3's theme that is implemented using Sphinx's internal search API so that it can be done completely client-side. If we don't want to use that, then we need to implement the autocomplete with something else, or completely remove it and fall back to redirecting the user to the `search.html` page). For example, [Wagtail's docs uses Algolia](https://github.com/wagtail/wagtail/blob/stable/6.2.x/docs/_templates/layout.html#L57-L87) (though that will likely change in the future). A feasible alternative is RTD's search API: https://docs.readthedocs.io/en/stable/server-side-search/api.html. However, if we do that, we need to consider that not all users of this theme use RTD as the hosting platform, so we need to make it optional.


With all those considerations, I think this is a worthwhile change 👍

**Comment by laymonage** [comment]
I can confirm that this works with Sphinx v8.1.3 as per the deployed preview:

https://github.com/user-attachments/assets/1073506b-179c-4dda-8111-7037695be175



and it also works with an older version of Sphinx e.g. 7.1.2


https://github.com/user-attachments/assets/aaae44cc-66b1-4acb-9e0b-4a2d5b548fc1

**Comment by lb-** [comment]
Thank you all! What an incredible bunch of digging. 

Should we try to document any of this somewhere? Either in the docs or the readme?
